version: '3.9'

services:
  frontend:
    build: ./frontend
    depends_on:
      - backend

  backend:
    build: ./backend
    expose:
      - "8000"
    environment:
      - DATABASE_URL=postgresql://postgres:Tosin@localhost:5432/app

  db:
    image: postgres:13
    environment:
      POSTGRES_SERVER: localhost
      POSTGRES_PASSWORD: Tosin
      POSTGRES_DB: app
      POSTGRES_PORT: 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - "8080:8080"

  proxy:
    image: jc21/nginx-proxy-manager:latest
    ports:
      - "8090:81"
      - "80:80"
      - "443:443"
    environment:
      - DISABLE_IPV6=true
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
      - ./nginx/nginx.conf:/data/nginx/custom/http_top.conf

volumes:
  postgres_data:

networks:
  networkfiles:
